---
title: "HW2"
author: "Da Bois BB"
date: "5/20/2021"
output: pdf_document
---

```{r}
library(pacman)
p_load(readr, data.table, dplyr, janitor, haven, here, 
       tidyverse, skimr, lfe, stargazer, quantreg, hrbrthemes, 
       tinytex, kableExtra, broom, sandwitch)
```

```{r}
# Load data
joe_mama = read_dta(here("MoneyExperiment.dta")) 
envelopes = joe_mama
```

```{r, Question 1}
reg_function_coef = function(x){
    reg = lm(x ~ public, 
               data = envelopes)
    coef = coef(reg)[2]
    return(coef)
}

reg_function_se = function(x){
    reg = lm(x ~ public, 
               data = envelopes)
    se = sqrt(diag(vcov(reg)))[2]
    return(se)
}

a <- lm(sex ~ public, data = joe_mama)
sqrt(diag(vcov(a)))[2]

```


```{r}
names(envelopes)

coef_tab_list <- tibble(Name = c("hhsize","schooling","age","sex","wealth","windex",
                                    "hyperbolic","hided_envelope")) %>% mutate(coef_tab_list = c(
house_size = reg_function_coef(envelopes$hhsize),
school_coeff = reg_function_coef(envelopes$schooling),
age_coeff = reg_function_coef(envelopes$age),
sex_coeff = reg_function_coef(envelopes$sex),
wealth_coeff = reg_function_coef(envelopes$wealth),
windex_coef = reg_function_coef(envelopes$windex),
hyperbolic_coef = reg_function_coef(envelopes$hyperbolic),
hide_coeff= reg_function_coef(envelopes$hided_envelope))) %>% 
  mutate(se_tab_list = c(
house_size = reg_function_se(envelopes$hhsize),
school_coeff = reg_function_se(envelopes$schooling),
age_coeff = reg_function_se(envelopes$age),
sex_coeff = reg_function_se(envelopes$sex),
wealth_coeff = reg_function_se(envelopes$wealth),
windex_coef = reg_function_se(envelopes$windex),
hyperbolic_coef = reg_function_se(envelopes$hyperbolic),
hide_coeff= reg_function_se(envelopes$hided_envelope)))





coef_tab_list %>% kbl(col.names = c("Name","Beta","SE"),
                      caption = "Table 2: Demographic Characteristics By Research Groups") %>% kable_paper("hover", full_width=F)

```





